
#define SPI_SCK_PIN 1
#define SPI_MOSI_PIN 2
#define SPI_MISO_PIN 3
#define SPI_PORT PORTB

#define SPI_MEM_VCC_EN_PIN 4
#define SPI_MEM_VCC_EN_PORT PORTB

#define whaever adasda

#define SPI_VCC_EN1_PIN 4
#define SPI_VCC_EN1_PORT PORTC
#define SPI_VCC_EN2_PIN 2
#define SPI_VCC_EN2_PORT PORTC
#define SPI_VCC_EN3_PIN 3
#define SPI_VCC_EN3_PORT PORTC
#define SPI_VCC_EN4_PIN 1
#define SPI_VCC_EN4_PORT PORTC
#define SPI_VCC_EN5_PIN 0
#define SPI_VCC_EN5_PORT PORTC
#define SPI_VCC_EN6_PIN 1
#define SPI_VCC_EN6_PORT PORTG
#define SPI_VCC_EN7_PIN 0
#define SPI_VCC_EN7_PORT PORTG
#define SPI_VCC_EN8_PIN 6
#define SPI_VCC_EN8_PORT PORTD
#define SPI_VCC_EN9_PIN 4
#define SPI_VCC_EN9_PORT PORTD
#define SPI_VCC_EN10_PIN 7
#define SPI_VCC_EN10_PORT PORTD
#define SPI_VCC_EN11_PIN 5
#define SPI_VCC_EN11_PORT PORTD
#define SPI_VCC_EN12_PIN 7
#define SPI_VCC_EN12_PORT PORTB

#define SPI_MEM_CS1_PIN 0
#define SPI_MEM_CS1_PORT PORTA
#define SPI_MEM_CS2_PIN 1
#define SPI_MEM_CS2_PORT PORTA
#define SPI_MEM_CS3_PIN 2
#define SPI_MEM_CS3_PORT PORTA
#define SPI_MEM_CS4_PIN 3
#define SPI_MEM_CS4_PORT PORTA
#define SPI_MEM_CS5_PIN 4
#define SPI_MEM_CS5_PORT PORTA
#define SPI_MEM_CS6_PIN 5
#define SPI_MEM_CS6_PORT PORTA
#define SPI_MEM_CS7_PIN 6
#define SPI_MEM_CS7_PORT PORTA
#define SPI_MEM_CS8_PIN 7
#define SPI_MEM_CS8_PORT PORTA
#define SPI_MEM_CS9_PIN 2
#define SPI_MEM_CS9_PORT PORTG
#define SPI_MEM_CS10_PIN 7
#define SPI_MEM_CS10_PORT PORTC
#define SPI_MEM_CS11_PIN 6
#define SPI_MEM_CS11_PORT PORTC
#define SPI_MEM_CS12_PIN 5
#define SPI_MEM_CS12_PORT PORTC

#define LDO_ON SPI_MEM_VCC_EN_PORT |= 1<<SPI_MEM_VCC_EN_PIN; // Turn LDO ON
#define LDO_OFF SPI_MEM_VCC_EN_PORT &= ~(1<<SPI_MEM_VCC_EN_PIN); // Turn LDO OFF

#define CS_MEM1_ON SPI_MEM_CS1_PORT |= 1<<SPI_MEM_CS1_PIN; // CS for MEM1 ON
#define CS_MEM2_ON SPI_MEM_CS2_PORT |= 1<<SPI_MEM_CS2_PIN; // CS for MEM2 ON
#define CS_MEM3_ON SPI_MEM_CS3_PORT |= 1<<SPI_MEM_CS3_PIN; // CS for MEM3 ON
#define CS_MEM4_ON SPI_MEM_CS4_PORT |= 1<<SPI_MEM_CS4_PIN; // CS for MEM4 ON
#define CS_MEM5_ON SPI_MEM_CS5_PORT |= 1<<SPI_MEM_CS5_PIN; // CS for MEM5 ON
#define CS_MEM6_ON SPI_MEM_CS6_PORT |= 1<<SPI_MEM_CS6_PIN; // CS for MEM6 ON
#define CS_MEM7_ON SPI_MEM_CS7_PORT |= 1<<SPI_MEM_CS7_PIN; // CS for MEM7 ON
#define CS_MEM8_ON SPI_MEM_CS8_PORT |= 1<<SPI_MEM_CS8_PIN; // CS for MEM8 ON
#define CS_MEM9_ON SPI_MEM_CS9_PORT |= 1<<SPI_MEM_CS9_PIN; // CS for MEM9 ON
#define CS_MEM10_ON SPI_MEM_CS10_PORT |= 1<<SPI_MEM_CS10_PIN; // CS for MEM10 ON
#define CS_MEM11_ON SPI_MEM_CS11_PORT |= 1<<SPI_MEM_CS11_PIN; // CS for MEM11 ON
#define CS_MEM12_ON SPI_MEM_CS12_PORT |= 1<<SPI_MEM_CS12_PIN; // CS for MEM12 ON

#define CS_MEM1_OFF SPI_MEM_CS1_PORT &= ~(1<<SPI_MEM_CS1_PIN); // VCC for MEM1 ON
#define CS_MEM2_OFF SPI_MEM_CS2_PORT &= ~(1<<SPI_MEM_CS2_PIN); // VCC for MEM2 ON
#define CS_MEM3_OFF SPI_MEM_CS3_PORT &= ~(1<<SPI_MEM_CS3_PIN); // VCC for MEM3 ON
#define CS_MEM4_OFF SPI_MEM_CS4_PORT &= ~(1<<SPI_MEM_CS4_PIN); // VCC for MEM4 ON
#define CS_MEM5_OFF SPI_MEM_CS5_PORT &= ~(1<<SPI_MEM_CS5_PIN); // VCC for MEM5 ON
#define CS_MEM6_OFF SPI_MEM_CS6_PORT &= ~(1<<SPI_MEM_CS6_PIN); // VCC for MEM6 ON
#define CS_MEM7_OFF SPI_MEM_CS7_PORT &= ~(1<<SPI_MEM_CS7_PIN); // VCC for MEM7 ON
#define CS_MEM8_OFF SPI_MEM_CS8_PORT &= ~(1<<SPI_MEM_CS8_PIN); // VCC for MEM8 ON
#define CS_MEM9_OFF SPI_MEM_CS9_PORT &= ~(1<<SPI_MEM_CS9_PIN); // VCC for MEM9 ON
#define CS_MEM10_OFF SPI_MEM_CS10_PORT &= ~(1<<SPI_MEM_CS10_PIN); // VCC for MEM10 ON
#define CS_MEM11_OFF SPI_MEM_CS11_PORT &= ~(1<<SPI_MEM_CS11_PIN); // VCC for MEM11 ON
#define CS_MEM12_OFF SPI_MEM_CS12_PORT &= ~(1<<SPI_MEM_CS12_PIN); // VCC for MEM12 ON

#define VCC_MEM1_ON SPI_VCC_EN1_PORT &= ~(1<<SPI_VCC_EN1_PIN); // VCC for MEM1 ON
#define VCC_MEM2_ON SPI_VCC_EN2_PORT &= ~(1<<SPI_VCC_EN2_PIN); // VCC for MEM2 ON
#define VCC_MEM3_ON SPI_VCC_EN3_PORT &= ~(1<<SPI_VCC_EN3_PIN); // VCC for MEM3 ON
#define VCC_MEM4_ON SPI_VCC_EN4_PORT &= ~(1<<SPI_VCC_EN4_PIN); // VCC for MEM4 ON
#define VCC_MEM5_ON SPI_VCC_EN5_PORT &= ~(1<<SPI_VCC_EN5_PIN); // VCC for MEM5 ON
#define VCC_MEM6_ON SPI_VCC_EN6_PORT &= ~(1<<SPI_VCC_EN6_PIN); // VCC for MEM6 ON
#define VCC_MEM7_ON SPI_VCC_EN7_PORT &= ~(1<<SPI_VCC_EN7_PIN); // VCC for MEM7 ON
#define VCC_MEM8_ON SPI_VCC_EN8_PORT &= ~(1<<SPI_VCC_EN8_PIN); // VCC for MEM8 ON
#define VCC_MEM9_ON SPI_VCC_EN9_PORT &= ~(1<<SPI_VCC_EN9_PIN); // VCC for MEM9 ON
#define VCC_MEM10_ON SPI_VCC_EN10_PORT &= ~(1<<SPI_VCC_EN10_PIN); // VCC for MEM10 ON
#define VCC_MEM11_ON SPI_VCC_EN11_PORT &= ~(1<<SPI_VCC_EN11_PIN); // VCC for MEM11 ON
#define VCC_MEM12_ON SPI_VCC_EN12_PORT &= ~(1<<SPI_VCC_EN12_PIN); // VCC for MEM12 ON

#define VCC_MEM1_OFF SPI_VCC_EN1_PORT |= 1<<SPI_VCC_EN1_PIN; // VCC for MEM1 OFF
#define VCC_MEM2_OFF SPI_VCC_EN2_PORT |= 1<<SPI_VCC_EN2_PIN; // VCC for MEM2 OFF
#define VCC_MEM3_OFF SPI_VCC_EN3_PORT |= 1<<SPI_VCC_EN3_PIN; // VCC for MEM3 OFF
#define VCC_MEM4_OFF SPI_VCC_EN4_PORT |= 1<<SPI_VCC_EN4_PIN; // VCC for MEM4 OFF
#define VCC_MEM5_OFF SPI_VCC_EN5_PORT |= 1<<SPI_VCC_EN5_PIN; // VCC for MEM5 OFF
#define VCC_MEM6_OFF SPI_VCC_EN6_PORT |= 1<<SPI_VCC_EN6_PIN; // VCC for MEM6 OFF
#define VCC_MEM7_OFF SPI_VCC_EN7_PORT |= 1<<SPI_VCC_EN7_PIN; // VCC for MEM7 OFF
#define VCC_MEM8_OFF SPI_VCC_EN8_PORT |= 1<<SPI_VCC_EN8_PIN; // VCC for MEM8 OFF
#define VCC_MEM9_OFF SPI_VCC_EN9_PORT |= 1<<SPI_VCC_EN9_PIN; // VCC for MEM9 OFF
#define VCC_MEM10_OFF SPI_VCC_EN10_PORT |= 1<<SPI_VCC_EN10_PIN; // VCC for MEM10 OFF
#define VCC_MEM11_OFF SPI_VCC_EN11_PORT |= 1<<SPI_VCC_EN11_PIN; // VCC for MEM11 OFF
#define VCC_MEM12_OFF SPI_VCC_EN12_PORT |= 1<<SPI_VCC_EN12_PIN; // VCC for MEM12 OFF