#CHI_COMM_ID_ACK 0x1A
#CHI_COMM_ID_NACK 0x15
CHI_COMM_ID_SCI_TM = 0x01
CHI_COMM_ID_STATUS = 0x02
#CHI_COMM_ID_EVENT 0x04
#CHI_COMM_ID_MODE 0x07
#CHI_COMM_ID_TIMESTAMP 0x08
#KISS constants
FEND = b'\xC0'
FESC =  b'\xDB'
TFEND = b'\xDC'
TFESC = b'\xDD'

ACK = b'\x1A'
NACK = b'\x15'
SCI_TM = b'\x01'
STATUS = b'\x02'
EVENT = b'\x04'
MODE = b'\x07'
TIMESTAMP = b'\x08'
